changes to config for noetic port
mjeronimo/carma-config pull request #1
Opened 2021-06-04 21:43 UTC by pmusau17

# PR Details

Changes to the docker compose files to test out the noetic port, this also includes a set of scripts to run the carma platform without breaking any of the main carma bash file. Primarily this pull request is to test if the noetic build is reproducible.

## Description

I had to change the docker compose file. Included a set of bash scripts.
## Related Issue

There are commented out sections of the original build files. I still need to work on fixing those/ need guidance as how they want this done.

## Motivation and Context

Building on Noetic is an intermediate step towards ROS2 port.

## How Has This Been Tested?

Tested on Ubuntu 20.04 laptop and virtual machine.

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-06-04 22:23 UTC, mjeronimo requested changes

2021-06-04 22:23 UTC, mjeronimo commented on development/build-image.sh
> +# if [[ $TAG = "develop-$CONFIG_NAME" ]]; then
Remove any dead blocks.

2021-06-04 22:23 UTC, mjeronimo commented on development/build-image.sh
> +# git checkout -- docker-compose.yml
Remove if not needed.

2021-06-04 22:23 UTC, mjeronimo commented on development/build-image.sh
> +docker tag $USERNAME/$IMAGE:$TAG $USERNAME/$IMAGE:latest
Is this correct? Should it be 'develop' ?

2021-06-04 22:23 UTC, mjeronimo commented on development/docker-compose.yml
> +    image: usdotfhwastol/carma-base:latest
I think we'll want to stay with 'develop'

2021-06-04 22:23 UTC, mjeronimo commented on development/set_local_config.sh
> +        'cat /opt/carma/vehicle/config/docker-compose.yml'
Looks like it wants a newline

2021-06-04 22:23 UTC, mjeronimo commented on development/start_up_noetic.sh
> +docker-compose -f docker-compose.yml -p carma up
newline

2021-06-07 12:01 UTC, closed without merging

2021-06-07 12:01 UTC, pmusau17 commented
Changes no longer needed